version: '3.5'
services:
 zabbix:
  image: zabbix/zabbix-server-mysql:ubuntu-5.0-latest
  container_name: zabbix
  ports:
   - "10051:10051"
  restart: always
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ./etc/alertscripts:/usr/lib/zabbix/alertscripts:ro
   - ./etc/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - /etc/hosts:/etc/hosts:ro
  env_file:
   - .env_db_mysql
   - .env_srv
  depends_on:
   - mysql

 web:
  image: zabbix/zabbix-web-apache-mysql:ubuntu-5.0-latest
  container_name: web
  ports:
   - "80:8080"
  restart: always
  volumes:
   - /etc/localtime:/etc/localtime:ro
  env_file:
   - .env_db_mysql
   - .env_web
  depends_on:
   - mysql
   - zabbix

 agent:
  image: zabbix/zabbix-agent:ubuntu-5.0-latest
  container_name: agent
  ports:
   - "10050:10050"
  restart: always
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ./etc/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
  env_file:
   - .env_agent
  privileged: true
  pid: "host"
  stop_grace_period: 5s
  depends_on:
   - zabbix
  links:                                                                                                                                                               
    - zabbix



 mysql:
  image: mysql:8.0
  container_name: mysql
  command:
   - mysqld
   - --character-set-server=utf8
   - --collation-server=utf8_bin
   - --default-authentication-plugin=mysql_native_password
  volumes:
   - ./mysql_db:/var/lib/mysql:rw
  env_file:
   - .env_db_mysql
  stop_grace_period: 1m

