CHANGE MASTER TO MASTER_HOST='5.101.120.5', MASTER_USER='repl', MASTER_PASSWORD='slavepassss';
START SLAVE;

CREATE USER 'zbx_monitor'@'%' IDENTIFIED BY '<password>';
GRANT USAGE,REPLICATION CLIENT,PROCESS,SHOW DATABASES,SHOW VIEW ON *.* TO 'zbx_monitor'@'%';

