version : '3'

services:
  mysql:
    image: mysql:5.7.30
    container_name: mysql
    volumes:
      - /app/db:/var/lib/mysql
      - /app/db_etc/slave.cnf:/etc/mysql/conf.d/repl.cnf
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: default_schema
    restart: always
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80
